version: 3

services:
  nginx-proxy:
    image: nginx:1.15.6-alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /var/nginx/conf:/etc/nginx:ro
      - /etc/letsencrypt/live/ropr.se/fullchain.pem:/etc/ssl/fullchain.pem
      - /etc/letsencrypt/live/ropr.se/privkey.pem:/etc/ssl/privkey.pem

  web:
    image: mhart/alpine:node
    container_name: web
    depends_on: nginx-proxy
    expose: 49160

  daysofrum:
    image: mhart/alpine:node
    container_name: daysofrum
    depends_on: nginx-proxy
    expose: 49260

networks:
  default:
    external:
      name: nginx-proxy
